-- 코드를 입력하세요

SELECT 
    REST_INFO.REST_ID, 
    REST_NAME,
    FOOD_TYPE, 
    FAVORITES, 
    ADDRESS, 
    COALESCE(ROUND(REST_REVIEW.AVG_SCORE, 2), 0)  AS SCORE 
FROM REST_INFO


LEFT JOIN (
SELECT
    REST_REVIEW.REST_ID,
    AVG(REVIEW_SCORE) AS AVG_SCORE
FROM 
    REST_REVIEW 
GROUP BY 
    REST_REVIEW.REST_ID
) REST_REVIEW ON REST_INFO.REST_ID = REST_REVIEW.REST_ID
WHERE 
    REST_REVIEW.AVG_SCORE IS NOT NULL
    AND LEFT(REST_INFO.ADDRESS, 2) = '서울'
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;