-- 코드를 입력하세요
SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) > 7 AND MONTH(START_DATE) < 11
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
) AND MONTH(START_DATE) > 7 AND MONTH(START_DATE) < 11
GROUP BY 
    MONTH(START_DATE), CAR_ID
ORDER BY
    MONTH(START_DATE) ASC, CAR_ID DESC